local ShopConfig = {
	Keyboards = {
		Banana = {
			Price = 250,
			DisplayName = "Banana",
		},
		Blue = {
			Price = 50,
			DisplayName = "Blue",
		},
		Broken = {
			Price = 200,
			DisplayName = "Broken",
		},
		Ghostly = {
			Price = 250,
			DisplayName = "Ghostly",
		},
		Mini = {
			Price = 60,
			DisplayName = "Mini",
		},
		XL = {
			Price = 190,
			DisplayName = "XL",
		},
		Yellow = {
			Price = 50,
			DisplayName = "Yellow",
		},
	},
}

return ShopConfig
