local ShopConfig = {
	Keyboards = {
		Banana = {
			Price = 100,
			DisplayName = "Banana",
		},
		Blue = {
			Price = 150,
			DisplayName = "Blue",
		},
		Broken = {
			Price = 200,
			DisplayName = "Broken",
		},
		Ghostly = {
			Price = 500,
			DisplayName = "Ghostly",
		},
		Mini = {
			Price = 300,
			DisplayName = "Mini",
		},
		XL = {
			Price = 400,
			DisplayName = "XL",
		},
		Yellow = {
			Price = 125,
			DisplayName = "Yellow",
		},
	},
}

return ShopConfig
